### ISSUE TITLE
Nvidia Blackwell Support

### ISSUE THREAD

**Issue by Zhynem** [snapotter-hq/SnapOtter#120]
### Before submitting

- [x] I searched existing issues and didn't find a duplicate

### Problem

When trying one of the AI tools it gives an error indicating an updated base image and pytorch are needed for Blackwell cards.

CUDA error (/paddle/third_party/flashattn/csrc/flash_attn/src/flash_fwd_launch_template.h:56): no kernel image is available for execution on the device","stack":"Error: /data/ai/venv/lib/python3.12/site-packages/torch/cuda/__init__.py:287: UserWarning:
NVIDIA RTX PRO 2000 Blackwell with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.

### Proposed solution

Change from cuda:12.6.3 to >= 12.8.1 when Blackwell support was added.
Install a compatible version of pytorch `pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu128`

### Alternatives considered

Cuda 13 base images / pytorch installs are also out now.

**Comment by neilp316** [comment]
Hitting the same problem here on an RTX 5060. Confirming this isn't isolated to the RTX PRO 2000 — same root cause.

**Environment:**
- GPU: RTX 5060
- Driver: 595.71.05
- Original venv: torch 2.7.0+cu126

**Symptom:** Same as above — `nvidia-smi` sees the GPU fine, but torch/onnxruntime/paddle can't use it. Log on startup showed `GPU: false` with torch not even loaded yet in my case (fresh AI bundle install).

**Workaround that worked for me:**
```
pip install --upgrade torch --index-url https://download.pytorch.org/whl/cu128
```
This pulled `torch 2.11.0+cu128`, which then triggered a dependency conflict with `torchvision 0.22.0+cu126` (requires `torch==2.7.0` exactly). Reinstalling torchvision against the cu128 index resolved most of it:
```
pip install torchvision --index-url https://download.pytorch.org/whl/cu128
```
Pip's resolver ended up settling on `torch 2.7.0+cu128` / `torchvision 0.22.0+cu126` — mismatched CUDA builds between the two, but `torch.cuda.is_available()` now returns `True` and GPU tools are working.

Also had to manually `pip install gdown` to fix an unrelated missing dependency for `codeformer-pip` surfaced during the same resolver run.

+1 for shipping a cu128+ (or CUDA 13) base image so this isn't a manual venv patch per user.

**Comment by killervette42** [comment]
having this issue too.  I am running this on unRaid.  When I tried your first pip commend I get this error:

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

Any ideas of what I should be doing?
